# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20180118_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
