# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20180118_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='enable',
            field=models.SmallIntegerField(choices=[(0, '\u4e0d\u91c7\u96c6'), (1, '\u91c7\u96c6')], default=1, verbose_name='\u662f\u5426\u91c7\u96c6'),
        ),
    ]
