# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('url', models.CharField(max_length=100, verbose_name='URL\u8fde\u63a5')),
                ('node', models.CharField(max_length=100, verbose_name='\u8282\u70b9')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='\u72b6\u6001')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'alarm',
                'verbose_name': '\u62a5\u8b66\u7ba1\u7406',
                'verbose_name_plural': '\u62a5\u8b66\u7ba1\u7406',
            },
        ),
    ]
