# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-16 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='\u8282\u70b9')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u533a\u57df')),
                ('url', models.CharField(max_length=100, verbose_name='URL\u8fde\u63a5')),
                ('http_code', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='\u72b6\u6001')),
                ('namelookup_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='DNS\u89e3\u6790\u57df\u540d')),
                ('connect_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u5efa\u7acbTCP\u8fde\u63a5')),
                ('pertransfer_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u7b2c\u4e00\u4e2a\u8fdc\u7a0b\u8bf7\u6c42\u63a5\u6536\u5230\u7b2c\u4e00\u4e2a\u5b57\u8282')),
                ('starttransfer_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u54cd\u5e94\u7b2c\u4e00\u4e2a\u5b57\u8282\u8fd4\u56de')),
                ('total_time', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u53d1\u9001\u4f1a\u6240\u6709\u7684\u76f8\u5e94\u6570\u636e')),
                ('size_download', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('head_size', models.IntegerField(blank=True, max_length=20, null=True, verbose_name='\u5934\u90e8\u5927\u5c0f')),
                ('speed_download', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True, verbose_name='\u4e0b\u8f7d\u901f\u5ea6')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'items',
                'verbose_name': '\u8be6\u60c5\u7ba1\u7406',
                'verbose_name_plural': '\u8be6\u60c5\u7ba1\u7406',
            },
        ),
    ]
