# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='items',
            name='head_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5934\u90e8\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='items',
            name='http_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='items',
            name='size_download',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='items',
            name='speed_download',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4e0b\u8f7d\u901f\u5ea6'),
        ),
    ]
