# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-18 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180118_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
